export default [
  {
    name:'管理中心',
    id:'a-1',
    path:'/adminCenter',
    icon:'',
    child:[
      {
        name:'项目管理',
        id:'a-1-1',
        path:'/adminCenter',
        icon:'',
      },
      {
        name:'新建项目',
        id:'a-1-2',
        path:'/addProject',
        icon:'',
      },
      {
        name:'检索中心',
        id:'a-1-3',
        path:'/retrievalCenter',
        icon:'',
      }
    ]
  },
  {
    name:'客户管理',
    id:'a-2',
    path:'/userAdmin',
    icon:'',
    child:[
      {
        name:'客户列表',
        id:'a-2-1',
        path:'/userAdmin',
        icon:'',
      },
      {
        name:'客户录入',
        id:'a-2-2',
        path:'/uesrInto',
        icon:'',
      }
    ]
  },
  {
    name:'扫描管理',
    id:'a-3',
    path:'/scanningAdmin',
    icon:'',
    child:[
      {
        name:'任务列表',
        id:'a-3-1',
        path:'/scanningAdmin',
        icon:'',
      },
      {
        name:'新建任务',
        id:'a-3-2',
        path:'/addTask',
        icon:'',
      }
    ]
  },
  {
    name:'信息搜集',
    id:'a-4',
    path:'/infoGathering',
    icon:'',
    child:[
      {
        name:'信息搜集',
        id:'a-4-1',
        path:'/infoGathering',
        icon:'',
      },
      {
        name:'新建搜集',
        id:'a-4-2',
        path:'/addGathering',
        icon:'',
      }
    ]
  },
  {
    name:'站点爬虫',
    id:'a-5',
    path:'/siteCrawler',
    icon:'',
    child:[
      {
        name:'爬虫列表',
        id:'a-5-1',
        path:'/siteCrawler',
        icon:'',
      },
      {
        name:'新建爬虫',
        id:'a-5-2',
        path:'/addCrawler',
        icon:'',
      },
      {
        name:'URL检索',
        id:'a-5-3',
        path:'/urlRetrieval',
        icon:'',
      }
    ]
  },
  {
    name:'节点管理',
    id:'a-6',
    path:'/nodeAdmin',
    icon:'',
    child:[
      {
        name:'节点列表',
        id:'a-6-1',
        path:'/nodeAdmin',
        icon:'',
      },
      {
        name:'添加节点',
        id:'a-6-2',
        path:'/addNode',
        icon:'',
      }
    ]
  },
  {
    name:'系统管理',
    id:'a-7',
    path:'/systemAdmin',
    icon:'',
    child:[
      {
        name:'用户列表',
        id:'a-7-1',
        path:'/systemAdmin',
        icon:'',
      },
      {
        name:'添加用户',
        id:'a-7-2',
        path:'/addUser',
        icon:'',
      }
    ]
  },
  {
    name:'代理地址池',
    id:'a-8',
    path:'/agentHref',
    icon:'',
    child:[
      {
        name:'用户列表',
        id:'a-8-1',
        path:'/agentHref',
        icon:'',
      }
    ]
  }
]
