export default [
  {
    name:'委托订单',
    id:'nav-1',
    path:'/nav-1',
    icon:'',
    child:[
      {
        name:'委托订单',
        id:'nav-1-1',
        path:'/entrustOrder',
        icon:'',
      },
    ]
  },
  {
    name:'调度派车',
    id:'nav-2',
    path:'/nav-2',
    icon:'',
    child:[
      {
        name:'车队管理',
        id:'nav-2-1',
        path:'/carsSet',
        icon:'',
      },
      {
        name:'调度单',
        id:'nav-2-2',
        path:'/dispatchOrder',
        icon:'',
      },
      {
        name:'运输跟踪',
        id:'nav-2-3',
        path:'/transportRecord',
        icon:'',
      },
      {
        name:'维修保养',
        id:'nav-2-4',
        path:'/maintenance',
        icon:'',
      },
      {
        name:'异常记录',
        id:'nav-2-5',
        path:'/abnormalRecord',
        icon:'',
      },
      {
        name:'延误记录',
        id:'nav-2-6',
        path:'/delayRecord',
        icon:'',
      }
    ]
  },
  {
    name:'结算中心',
    id:'nav-3',
    path:'/nav-3',
    icon:'',
    child:[
      {
        name:'应收费用',
        id:'nav-3-1',
        path:'/realCost',
        icon:'',
      },
      {
        name:'应收对账单',
        id:'nav-3-2',
        path:'/realBill',
        icon:'',
      },
      {
        name:'发票管理',
        id:'nav-3-3',
        path:'/invoiceSet',
        icon:'',
      }
    ]
  },
  {
    name:'统计报表',
    id:'nav-4',
    path:'/nav-4',
    icon:'',
    child:[
      {
        name:'订单统计',
        id:'nav-4-1',
        path:'/orderStats',
        icon:'',
      },
      {
        name:'运输分析',
        id:'nav-4-2',
        path:'/transportAnls',
        icon:'',
      },
      {
        name:'应收费用报表',
        id:'nav-4-3',
        path:'/realCostECharts',
        icon:'',
      }
    ]
  },
  {
    name:'基础数据',
    id:'nav-5',
    path:'/nav-5',
    icon:'',
    child:[
      {
        name:'承运商管理',
        id:'nav-5-1',
        path:'/carrierSet',
        icon:'',
      },
      {
        name:'委托客户管理',
        id:'nav-5-2',
        path:'/clientSet',
        icon:'',
      },
      {
        name:'收发货人管理',
        id:'nav-5-3',
        path:'/consignorSet',
        icon:'',
      },
      {
        name:'车辆管理',
        id:'nav-5-4',
        path:'/carSet',
        icon:'',
      },
      {
        name:'司机管理',
        id:'nav-5-5',
        path:'/driverSet',
        icon:'',
      }
    ]
  },
  {
    name:'权限管理',
    id:'nav-6',
    path:'/nav-6',
    icon:'',
    child:[
      {
        name:'用户管理',
        id:'nav-6-1',
        path:'/userSet',
        icon:'',
      },
      {
        name:'角色管理',
        id:'nav-6-2',
        path:'/roleSet',
        icon:'',
      },
      {
        name:'数据字典',
        id:'nav-6-3',
        path:'/dataDictionary',
        icon:'',
      },
      {
        name:'操作日志',
        id:'nav-6-4',
        path:'/operationLog',
        icon:'',
      }
    ]
  }
]
